### ISSUE TITLE
VSCode - Unload java process

### ISSUE THREAD

**Issue by paoloantinori** [camel-tooling/camel-language-server#207] opened 2019-02-04 09:27 UTC
# Issue informations

### Environment

- Apache Camel Language Server release version date: `0.0.13`
- OS:
    - [x] Linux (*RHEL*, *Fedora*, *Ubuntu*, ...)
    - [ ] Windows
    - [ ] Mac OS
- Apache Camel Client for:
    - [ ] Eclipse
    - [x] VS Code
    - [ ] Eclipse Che
    - [ ] OpenShift.io

### Description of wrong behavior

- My VScode instance seems not being capable to unload the memory hungry `language-server.jar` from memory, not even when I have no Camel related file open.

### Exact steps to reproduce issue

1. not sure, I've just noticed this running memory checking commands, showing the problem
2. ...
3. ...

### Expected behaviour

- not to consume all that ram when not really needed

### Screenshot (*optional*)

- ...
![screenshot from 2019-02-04 10-24-59](https://user-images.githubusercontent.com/1520602/52199754-43751580-2867-11e9-9c53-a48581cd0bbf.png)
![screenshot from 2019-02-04 10-26-29](https://user-images.githubusercontent.com/1520602/52199797-5ee02080-2867-11e9-8151-77120acf1ee7.png)

**Comment by apupier** [comment] 2019-02-04 10:17
it is to the responsibility to VS Code to shutdown the Language server. As there is a single language server process, it seems normal to have one running. Might worth to check anyway if there is away to force the shutdown of the language server when there is no more opened files.

What is really not normal is the 10.9G of memory used.
Have you opened some specific camel or java file? Can you take a Java memory heap dump when you reproduce? (jstack command can be used https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jstack.html )

**Comment by apupier** [comment] 2019-02-04 12:38
I tried to monitor memory but even with 5 files of Java or xml, the max amount of memory taken is 15M which is going back to 7M after closing the files. Having the Heap dump would really help. Some hints on which kind of features/files/projects were used too.

**Comment by apupier** [comment] 2019-02-11 09:41
@paoloantinori is the issue occurred again?

**Comment by apupier** [comment] 2019-03-21 13:21
closing as we cannot reproduce and we don't have enough information to investigate.

Please reopen if you reproduce or if you have more information (like a Heap Dump for instance)

**Closed by apupier** 2019-03-21 13:21 UTC
